
=head1 NAME

Inkscape - editor SVG (Scalable Vector Graphics).

=head1 SYNOPSIS

C<inkscape [voľby] [názov súboru ...]>

voľby:

    -?, --help        
        --usage       
    -V, --version

    -f, --file=NÁZOVSÚBORU               

    -e, --export-png=NÁZOVSÚBORU         
    -a, --export-area=x0:y0:x1:y1     
    -C, --export-area-canvas
    -D, --export-area-drawing
        --export-area-snap
    -i, --export-id=ID     
    -j, --export-id-only     
    -t, --export-use-hints
    -b, --export-background=FARBA     
    -y, --export-background-opacity=HODNOTA     
    -d, --export-dpi=DPI              
    -w, --export-width=ŠÍRKA          
    -h, --export-height=VÝŠKA        

    -P, --export-ps=NÁZOVSÚBORU
    -E, --export-eps=NÁZOVSÚBORU
    -A, --export-pdf=NÁZOVSÚBORU

    -T, --export-text-to-path
        --export-bbox-page 

    -l, --export-plain-svg=NÁZOVSÚBORU             

    -p, --print=PRINTER

    -I, --query-id=ID     
    -X, --query-x
    -Y, --query-y
    -W, --query-width
    -H, --query-height
    -S, --query-all

    -x, --extension-directory

        --verb-list
        --verb=VERB-ID
        --select=OBJECT-ID

        --shell

    -g, --with-gui                    
    -z, --without-gui                 

        --vacuum-defs

        --g-fatal-warnings

=head1 OPIS

B<Inkscape> je editor súborov vektorovej grafiky vo formáte
B<Scalable Vector Graphics (SVG)> s grafickým rozhraním, ktorého
schopnosti sú podobné B<Adobe Illustrator>, B<CorelDraw>, B<Xara Xtreme>,
atď. Medzi vlastnosti Inkscape patria všestranné tvary, bézierove krivky,
kreslenie voľbou rukou, viacriadkový text, text na ceste, alpha blending,
ľubovoľné afínne transformácie, farebné prechody a výplň vzorkou,
úprava uzlov, mnohé formáty na export a import vrátane PNG a PDF,
zoskupovanie, vrstvy, živé klony a veľa iného. Rozhranie je navrhnuté pre
komfortné a efektívne ovládanie pre skúseného používateľa, pričom dodržiava
štandardy B<GNOME>, takže používateľ oboznámený s inými aplikáciami GNOME
si môže ovládanie rozhrania rýchlo osvojiť.

B<SVG> je štandardný W3C XML formát pre dvojrozmernú vektorovú grafiku.
Umožňuje definíciu objektov kresby pomocou bodov, ciest a primitívnych
tvarov. Farby, fonty, šírka ťahu atď sa pri týchto objektoch uvádzajú ako
atribúty „štýlu“. Zámer je taký, že keďže SVG je štandard a jeho súbory sú
text/xml, bude možné použiť SVG súbory vo veľkom počte programov v širokom
spektre aplikácií.

B<Inkscape> používa SVG ako svoj natívny formát dokumentu a jeho cieľom je
stať sa kresliacim programom plne konformným SVG súborom, dostupným open
source komunite.


=head1 VOĽBY

=over 8

=item B<-?>, B<--help>

Zobrazí správu s pomocou

=item B<-V>, B<--version>

Zobrazí verziu a dátum zostavenia Inkscape.

=item B<-a> I<x0:y0:x1:y1>, B<--export-area>=I<x0:y0:x1:y1>

Pri exporte PNG, nastaví exportovanú oblasť v používateľských jednotkách
SVG (anonymné jednotky dĺžky bežne používané v Inkscape SVG). Štandardne sa
exportuje celé kresliace plátno dokumentu. Bod (0,0) je spodný dolný roh.

=item B<-C>, B<--export-area-canvas>

Pri exporte NG, PDF, PS a EPS je exportovaná oblasť celé kresliace plátno dokumentu
(stránka). Toto je šandardné nastavenie pre PNG, PDF a PS, takže ju nemusíte uvádzať
ak nepoužívate --export-id na exportovanie konkrétneho objektu. Pri exporte EPS to
však nie je šandardné nastavenie. Naviac pri EPS neumožňuje špecifikácia formátu aby
bolo ohraničenie väčšie ako obsah dokumentu. To znamená, že ak pri exporte EPS použijete
--export-area-canvas, ohraničenie plátna sa oreže dnu na ohraničenie objektu ak je menšie.

=item B<-D>, B<--export-area-drawing>

Pri exporte PNG, PDF, PS a EPS je exportovaná oblasť celá kresba (nie plátno), t.j. ohraničenie
všetkých objektov dokumentu (alebo exportovaného objektu ak je použité --export-id). 
S touto voľbou budú na exportovanom obrázku iba viditeľné objekty dokumentu bez
okrajov alebo orezania. Toto je štandardná exportná oblasť pre EPS. Pri PNG
je možné použiť túto voľbu v kombinácii s --export-use-hints.

=item B<--export-area-snap>

Pri exporte png prichytí oblasť exportu smerom von na najbližšiu celočíselnú používateľskú jednotku SVG (px).
Ak používate štandardné rozlíšenie na export 90 dpi a vaša grafika je zarovnaná na pixely aby sa minimalizoval
antialiasing, tento prepínač vám umožní zachovať toto zarovnanie aj ak exportujete ohraničenie nejakého
objektu (pmocou --export-id alebo --export-area-drawing), ktoré samotné nie je zarovnané na pixely.

=item B<-b> I<FARBA>, B<--export-background>=I<FARBA>

Farba pozadia exportovaného PNG.
Toto môže byť akýkoľvek reťazec špecifikujúci farbu, ktorý SVG podporuje, napr.
„#ff007f“ alebo „rgb(255, 0, 128)“.
Ak nie je nastavená, použije sa farba nastavená v Inkscape v dialógu Možnosti dokumentu (uložená v atribúte pagecolor= v sodipodi:namedview).

=item B<-d> I<DPI>, B<--export-dpi>=I<DPI>

Použité rozlíšenie na export PNG.
Tiež sa používa pri rasterizácii filtrovaných objektov pri exporte do PS, EPS a PDF (ak neuvediete
--export-ignore-filters na potlačenie rasterizácie).
Štandardne 90, čo zodpovedá 1 používateľskej jednotke SVG.
(px, tiež nazývaná „používateľská jednotka“) exportovanej na 1 pixel bitmapy.
Táto hodnota má precedenciu pred odporúčaným DPI pri použití s prepínačom --export-use-hints.

=item B<-e> I<NÁZOVSÚBORU>, B<--export-png>=I<NÁZOVSÚBORU>

Názov súboru pre export PNG.
Ak už existuje, bude prepísaní bez pýtania sa.

=item B<-f> I<NÁZOVSÚBORU>, B<--file>=I<NÁZOVSÚBORU>

Otvorí zadané dokumenty.
Je možné vynechať reťazec voľby, t.j. možete uviesť zoznam súborov bez -f.

=item B<-g>, B<--with-gui>

Pokúsiť sa použiť GUI (na unixových systémoch, použiť X server aj keď nie je nastavená premenná $DISPLAY).

=item B<-h> I<VÝŠKA>, B<--export-height>=I<VÝŠKA>

Výška generovaných bitmáp v pixeloch. Táto hodnota má precedenciu pred
nastavením --export-dpi (alebo odporúčaním DPI pri použití s prepínačom --export-use-hints). 

=item B<-i> I<ID>, B<--export-id>=I<ID>

Pri exporte PNG, PS, EPS a PDF hodnota atrihútu id objektu, ktorý chcete
exportovať z dokumentu. Žiadne iné objekty sa neexportujú. Štandardne sa
exportuje ohraničenie objektu. To môžete zmeniť použitím voľby
--export-area (iba pri PNG) alebo --export-area-canvas.

=item B<-j>, B<--export-id-only>

Exportovať do PNG iba objekt s id zadaným v --export-id. Všetky ostatné objekty sa skryjú a
nezobrazia sa v exporte ani keď prekrúvajú exportovaný objekt. Ak nie je uvedené --export-id,
táto voľba sa ignoruje. Pri exporte PDF je toto štandardná voľba, takže jej uvedenie nemá žiadny vplyv.

=item B<-l>, B<--export-plain-svg>=I<NÁZOVSÚBORU>

Exportovať dokumenty do formátu čisté SVG, bez menných priestorov sodipodi: alebo inkscape: namespaces a bez metadát RDF.

=item B<-x>, B<--extension-directory>

Vypíše aktuálny adresár rozšírení, ktorý bol nastavený pre inkscape a potom
skončí. Využívajú to externé rozšírenia aby použili rovnakú konfiguráciu ako
pôvodná inštalácia Inkscape.

=item B<--verb-list>

Vypíše všetky slovesá dostupné v Inkscape podľa ID. Tieto ID možno použiť
pri definovaní klávesových máp alebo menu. Tiež ich možno použiť na
príkazovom riadku s voľbou --verb.

=item B<--verb>=I<VERB-ID>, B<--select>=I<OBJECT-ID>

Tieto dve voľby spolu poskytujú základné možnosti skriptovania v Inkscape
z príkazového riadka. Obe sa môžu na príkazovom riadku vyskytovať
ľubovoľný počet krát a vykonajú sa v tomto poradí na každom určenom
dokumente.

Príkaz --verb vykoná uvedené sloveso ako keby bolo zavolané z menu alebo
klávesovou skratkou. Dialógy sa objavia ak sú súčasťou slovesa. Ak chcete
vypísať zoznam dostupných ID, použite voľby príkazového riadka
--verb-list.

Príkaz --select spôsobí výber objektov s uvedeným ID.
To umožňuje vykonávanie slovies na nich.
Ak chcete zrušiť všetky výbery, použite --verb=EditDeselect. ID objektov
sú dostupné v závislosti na dokumente, ktorý sa má načítať.

=item B<-p> I<TLAČIAREŇ>, B<--print>=I<TLAČIAREŇ>

Vytlačí dokumenty na určenej tlačiarni pomocou „lpr -P TLAČIAREŇ“.
Ak chcete výstup poslať rúrou inému príkazu, môžete použiť „| PRÍKAZ“
alebo „> NÁZOVSÚBORU“ ak chcete namiesto tlačenia zapísať výstup v PostScripte do súboru.
Pamätajte na to, že musíte použiť vhodné úvodzovky pre váš shell, napr.

inkscape --print='| ps2pdf - mydoc.pdf' mydoc.svg

=item B<-t>, B<--export-use-hints>

Použiť názov exportovaného súboru a atribút DPI uložené v exportovanom objekte (iba s voľbou --export-id).
Tieto údaje sa nastavujú automaticky keď exportujete výber z grafického rozhrania Inkscape.
Takže napr. ak exportujete útvar s id="path231" ako /home/me/shape.png pri 300 dpi z dokument.svg z grafického rozhrania Inkscape a uložíte dokument, neskôr budete môcť exportovať útvar
do rovnakého súboru s rovnakým rozlíšením jednoducho spustením

inkscape -i path231 -t document.svg

Ak spolu s touto voľbou použijete --export-dpi, --export-width alebo --export-height
bude sa atribút DPI ignorovať a použije sa hodnota zadaná na príkazovom riadku.
Ak spolu s touto voľbou použijete --export-png, 
bude sa atribút názvov súboru ignorovať a použije sa hodnota zadaná na príkazovom riadku.

=item B<-w> I<ŠÍRKA>, B<--export-width>=I<ŠÍRKA>

Výška generovaných bitmáp v pixeloch. Táto hodnota má precedenciu pred nastavením --export-dpi
(alebo odporúčaním DPI pri použití s prepínačom --export-use-hints). 

=item B<-y> I<HODNOTA>, B<--export-background-opacity>=I<HODNOTA>

Krytie pozadia exportovaných súborov PNG.
Toto môže byť hodnota buď medzi 0.0 a 1.0 (kde 0.0 znamená celkom priehľadné a 1.0 plné krytie)
alebo väčšia ako 1 do 255 (kde 255 znamená plné krytie).
Ak nie je hodnota nastavená a nepoužije sa voľba -b,
použije sa krytie stránky nastavené v Inkscape v dialógu Vlastnosti dokumentu (uložené v atribúte inkscape:pageopacity=  sodipodi:namedview).
Ak nie je hodnota nastavená a použije sa voľba -b
použije sa hodnota 255 (plné krytie).

=item B<-P> I<NÁZOVSÚBORU>, B<--export-ps>=I<NÁZOVSÚBORU>

Exportovať dokumenty do formátu PostScript. Pamätajte, že PostScript nepodporuje priesvitnosť, takže akékoľvek priesvitné objekty v pôvodnom SVG sa automaticky rasterizujú. Priložia sa použité písma alebo podmnožina použitých znakov. Štandardná oblasť exportu je plátno a môžete ju nastaviť na kresbu pomocou --export-area-drawing.
Ak chcete exportovať jediný objekt, môžete použiť --export-id (všetky ostatné sa skryjú); v tom prípade
bude oblasťou exportu ohraničenie uvedeného objektu, ale možno ho nastaviť na plátno voľbou --export-area-canvas.

=item B<-E> I<NÁZOVSÚBORU>, B<--export-eps>=I<NÁZOVSÚBORU>

Exportovať dokumenty do formátu Encapsulated PostScript. Pamätajte, že PostScript nepodporuje priesvitnosť, takže akékoľvek priesvitné objekty v pôvodnom SVG sa automaticky rasterizujú. Priložia sa použité písma alebo podmnožina použitých znakov. Štandardná oblasť exportu je kresba a môžete ju však nastaviť na plátno, pozrite si však obmedzenia v popise voľby --export-area-drawing. Ak chcete exportovať jediný objekt, môžete použiť --export-id (všetky ostatné sa skryjú).

=item B<-A> I<NÁZOVSÚBORU>, B<--export-pdf>=I<NÁZOVSÚBORU>

Exportovať dokumenty do formátu PDF format. Tento formát zachováva priesvitnosť z pôvodného SVG.
Priložia sa použité písma alebo podmnožina použitých znakov.
Štandardná oblasť exportu je plátno a môžete ju nastaviť na kresbu pomocou --export-area-drawing.
Ak chcete exportovať jediný objekt, môžete použiť --export-id (všetky ostatné sa skryjú); v tom prípade
bude oblasťou exportu ohraničenie uvedeného objektu, ale možno ho nastaviť na plátno voľbou --export-area-canvas.

=item B<-T>, B<--export-text-to-path>

Konvertovať pri exporte textové objekty na cesty kde sa dá (pri exporte PS, EPS a PDF).

=item B<--export-ignore-filters>

Exportovať objekty s filtrami (napr. tie s rozostrenám) ako vektorovú grafiku a ignorovať filtre (pri exporte PS, EPS a PDF). 
Štandardne sa všetky objekty s filtrami rasterizujú s rozlíšením --export-dpi (štandardne 90 dpi) čím sa zachová ich vzhľad.

=item B<-I>, B<--query-id>

Nastaviť ID objektu, ktoré rozmery zisťujeme. Ak nie je nastavené, voľby požiadavky
vrátia rozmer kresby (t.j. všetkých objektov dokumentu), nie stránky či zobrazenia.

=item B<-X>, B<--query-x>

Zistiť súradnicu X kresby alebo, ak je určený, objektu s --query-id. Vrátená hodnota je v px (používateľské jednotky SVG). 

=item B<-Y>, B<--query-y>

Zistiť súradnicu Y kresby alebo, ak je určený, objektu s --query-id. Vrátená hodnota je v px (používateľské jednotky SVG). 

=item B<-W>, B<--query-width>

Zistiť šírku kresby alebo, ak je určený, objektu s --query-id. Vrátená hodnota je v px (používateľské jednotky SVG). 

=item B<-H>, B<--query-height>

Zistiť výšku kresby alebo, ak je určený, objektu s --query-id. Vrátená hodnota je v px (používateľské jednotky SVG). 

=item B<-S>, B<--query-all>

Vypíše zoznam všetkých objektov v dokumente SVG s definovaným id spolu s ich
súradnicou x,y, šírkou a výškou vo formáte s hodnotami oddelenom čiarkami.

=item B<--shell>

With this parameter, Inkscape will enter an interactive command line shell mode. In this
mode, you type in commands at the prompt and Inkscape executes them, without you having
to run a new copy of Inkscape for each command. This feature is mostly useful for
scripting and server uses: it adds no new capabilities but allows you to improve the
speed and memory requirements of any script that repeatedly calls Inkscape to perform
command line tasks (such as export or conversions). Each command in shell mode must be a
complete valid Inkscape command line but without the Inkscape program name, for example
"file.svg --export-pdf=file.pdf".

=item B<--vacuum-defs>

Remove all unused items from the <lt>defs<gt> section of the SVG file.  If this
option is invoked in conjunction with --export-plain-svg, only the exported file
will be affected.  If it is used alone, the specified file will be modified in place.

=item B<-z>, B<--without-gui>

Do not open the GUI (on Unix, do not use X server); only process the files from console.
This is assumed for -p, -e, -l, and --vacuum-defs options. 

=item B<--g-fatal-warnings>

This standard GTK option forces any warnings, usually harmless, to cause Inkscape to
abort (useful for debugging).

=item B<--usage>

Display a brief usage message.

=back

=head1 KONFIGURÁCIA

The main configuration file is located in ~/.config/Inkscape/preferences.xml; it stores
a variety of customization settings that you can change in Inkscape (mostly in the
Inkscape Preferences dialog).  Also in the subdirectories there, you can place your own:

B<$HOME>/.config/Inkscape/extensions/ - extension effects.

B<$HOME>/.config/Inkscape/icons/ - icons.

B<$HOME>/.config/Inkscape/keys/ - keyboard maps.

B<$HOME>/.config/Inkscape/templates/ - new file templates.

=head1 DIAGNOSTIKA

The program returns zero on success or non-zero on failure.

A variety of error messages and warnings may be printed to STDERR or
STDOUT.  If the program behaves erratically with a particular SVG file
or crashes, it is useful to look at this output for clues.

=head1 PRÍKLADY

While obviously B<Inkscape> is primarily intended as a GUI application,
it can be used for doing SVG processing on the commandline as well.

Open an SVG file in the GUI:

    inkscape filename.svg

Print an SVG file from the command line:

    inkscape filename.svg -p '| lpr'

Export an SVG file into PNG with the default resolution of 90dpi (one SVG user unit translates to one bitmap pixel):

    inkscape filename.svg --export-png=filename.png

Same, but force the PNG file to be 600x400 pixels:

    inkscape filename.svg --export-png=filename.png -w600 -h400

Same, but export the drawing (bounding box of all objects), not the page:

    inkscape filename.svg --export-png=filename.png --export-area-drawing

Export to PNG the object with id="text1555", using the output filename and 
the resolution that were used for that object last time when it was exported from the GUI:

    inkscape filename.svg --export-id=text1555 --export-use-hints

Same, but use the default 90dpi resolution, specify the filename, 
and snap the exported area outwards to the nearest whole SVG user unit values 
(to preserve pixel-alignment of objects and thus minimize antialiasing):

    inkscape filename.svg --export-id=text1555 --export-png=text.png --export-snap-area

Convert an Inkscape SVG document to plain SVG:  

    inkscape filename1.svg --export-plain-svg=filename2.svg

Convert an SVG document to EPS, converting all texts to paths:

    inkscape filename.svg --export-eps=filename.eps --export-text-to-path

Query the width of the object with id="text1555":

    inkscape filename.svg --query-width --query-id text1555

Duplicate the object with id="path1555", rotate the duplicate 90 degrees, save SVG, and quit:

    inkscape filename.svg --select=path1555 --verb=EditDuplicate --verb=ObjectRotate90 --verb=FileSave --verb=FileClose


=head1 PROSTREDIE

B<DISPLAY> to get the default host and display number.

B<TMPDIR> to set the default path of the directory to use for temporary
files.  The directory must exist.

=head1 TÉMY

To load different icons sets instead of the default
B<$PREFIX>/share/inkscape/icons/icons.svg file, the directory
B<$HOME>/.inkscape/icons/ is used.  Icons are loaded by name
(e.g. I<fill_none.svg>), or if not found, then from I<icons.svg>.  If the
icon is not loaded from either of those locations, it falls back to the
default system location.

The needed icons are loaded from SVG files by searching for the SVG id with
the matching icon name.  (For example, to load the "fill_none" icon from
a file, the bounding box seen for SVG id "fill_none" is rendered as the
icon, whether it comes from I<fill_none.svg> or I<icons.svg>.)



=head1 ĎALŠIE INFORMÁCIE

The canonical place to find B<Inkscape> info is at
http://www.inkscape.org/.  The website has news, documentation,
tutorials, examples, mailing list archives, the latest released
version of the program, bugs and feature requests databases, forums,
and more.

=head1 POZRI AJ

potrace, cairo, rsvg(1), batik, ghostscript, pstoedit.

SVG compliance test suite:  http://www.w3.org/Graphics/SVG/Test/

SVG validator:  http://jiggles.w3.org/svgvalidator/

I<Scalable Vector Graphics (SVG) 1.1 Specification>
I<W3C Recommendation 14 January 2003>
L<http://www.w3.org/TR/SVG11/>

I<Scalable Vector Graphics (SVG) 1.2 Specification>
I<W3C Working Draft 13 November 2003>
L<http://www.w3.org/TR/SVG12/>

I<SVG 1.1/1.2/2.0 Requirements>
I<W3C Working Draft 22 April 2002>
L<http://www.w3.org/TR/SVG2Reqs/>

I<Document Object Model (DOM): Level 2 Core>
I<Arnaud Le Hors et al editors, W3C>
L<http://www.w3.org/TR/DOM-Level-2-Core/>


=head1 POZNÁMKY KU GRAFICKÉMU ROZHRANIU

To learn Inkscape's GUI operation, read the tutorials in Help > Tutorials.

Apart from SVG, Inkscape can import (File > Import) most bitmap formats 
(PNG, BMP, JPG, XPM, GIF, etc.), plain text (requires Perl), PS and EPS (requires Ghostscript), PDF 
and AI format (AI version 9.0 or newer). 

Inkscape exports 32-bit PNG images (File > Export) as well as AI, PS, EPS, PDF, DXF, 
and several other formats via File > Save as.

Inkscape can use the pressure and tilt of a graphic tablet pen for width, angle,
and force of action of several tools, including the Calligraphic pen.

Inkscape includes a GUI front-end to the Potrace bitmap tracing engine
(http://potrace.sf.net) which is embedded into Inkscape.

Inkscape can use external scripts (stdin-to-stdout filters) that are represented by
commands in the Effects menu. A script can have a GUI dialog for setting various
parameters and can get the IDs of the selected objects on which to act via the command
line. Inkscape comes with an assortment of effects written in Python.

=head1 KLÁVESOVÉ VÄZBY

To get a complete list of keyboard and mouse shortcuts, view doc/keys.html, or use the Keys and Mouse command in Help menu.

=head1 CHYBY

Many bugs are known; please refer to the website (inkscape.org) for reviewing the reported ones and to
report newly found issues.  See also the Known Issues section in the Release Notes for
your version (file `NEWS').

=head1 AUTORI

This codebase owes its existance to a large number of contributors
throughout its various incarnations.  The following list is certainly
incomplete, but serves to recognize the many shoulders on which this
application sits:

[% INCLUDE "AUTHORS" %]

This man page was put together by Bryce Harrington
E<lt>brycehar@bryceharrington.comE<gt>.

=head1 HISTÓRIA

The codebase that would become Inkscape began life in 1999 as the
program Gill, the GNOME Illustrator application, created by Raph
Levien.  The stated objective for Gill was to eventually support all of
SVG.  Raph implemented the PostScript bezier imaging model, including
stroking and filling, line cap style, line join style, text, etc.  
Raph's Gill page is at http://www.levien.com/svg/.  Work on Gill appears
to have slowed or ceased in 2000.

The next incarnation of the codebase was to become the highly popular
program Sodipodi, led by Lauris Kaplinski.  The codebase was turned
into a powerful illustration program over the course of several
year's work, adding several new features, multi-lingual support, porting
to Windows and other operating systems, and eliminating dependencies.

Inkscape was formed in 2003 by four active Sodipodi developers, Bryce
Harrington, MenTaLguY, Nathan Hurst, and Ted Gould, wanting to take a
different direction with the codebase in terms of focus on
SVG compliance, interface look-and-feel, and a desire to open
development opportunities to more participants.  The project progressed
rapidly, gaining a number of very active contributors and features.

Much work in the early days of the project focused on code stablization
and internationalization.  The original renderer inherited from Sodipodi
was laced with a number of mathematical corner cases which led to
unexpected crashes when the program was pushed beyond routine uses; this
renderer was replaced with Livarot which, while not perfect either, was
significantly less error prone.  The project also adopted a practice of
committing code frequently, and encouraging users to run developmental
snapshots of the program; this helped identify new bugs swiftly, and
ensure it was easy for users to verify the fixes.  As a result, Inkscape
releases have generally earned a reputation for being robust and
reliable.

Similarly, efforts were taken to internationalize and localize the
interface, which has helped the program gain contributors worldwide.

Inkscape has had a beneficial impact on the visual attractiveness of
Open Source in general, by providing a tool for creating and sharing
icons, splash screens, website art, and so on.  In a way, despite being
"just an drawing program", Inkscape has played an important role in
making Open Source more visually stimulating to larger audiences.

=head1 AUTORSKÉ PRÁVA A LICENCIA

B<Copyright (C)> 1999-2008 by Authors.  

B<Inkscape> is free software; you can redistribute it and/or modify it
under the terms of the GPL.  


=for comment
$Date: 2009-04-30 23:09:18 +0200 (Thu, 30 Apr 2009) $
