#!/bin/sh

inf=$1
outf=$2
datestr=`date`

echo "" > ${outf}
echo "/* ###################################################" >> ${outf}
echo "## This file generated by wrap_swig_module.sh from" >> ${outf}
echo "## ${inf} on ${datestr}" >> ${outf}
echo "## DO NOT EDIT" >> ${outf}
echo "################################################### */" >> ${outf}
echo "" >> ${outf}

echo "static char *inkscape_module_script =" >> ${outf}
echo "\"\n\"" >> ${outf}

cat ${inf} | \
sed -e 's/\"/\\"/g' -e 's/^/\"/g' -e 's/$/\\n\"/g' >> ${outf}

echo "\"\n\";" >> ${outf}






