#!/bin/bash
# update-makefiles.sh
# (c) 2009 Krzysztof Kosiński
# Licensed under GNU GPL; see the file COPYING for details
#
# This script regenerates the makefiles for the subdirectories of hicolor.

OLD_IFS=$IFS
IFS=$'\0'

for dir_size in *; do
if test -d $dir_size; then

for dir in $dir_size/*; do
if test -d $dir; then
	ICONS_DATA=$(find $dir -name '*.svg' -and -not -name '*.svn*' -printf '\t%f \\\n' \
		| sort \
		| sed -e '$s|\\||')
SIZE=$(echo $dir_size | sed -e 's|x.*||')
CONTEXT=$(echo $dir | sed -e 's|^.*/||')
echo \
'themedir = $(pkgdatadir)/icons/hicolor
size = '$SIZE'
context = '$CONTEXT'

iconsdir = $(themedir)/$(size)/$(context)

# Auto-generated by update-makefiles.sh
# Re-run the script to update.

icons_DATA = \
'$ICONS_DATA'

EXTRA_DIST = $(icons_DATA)' > $dir/Makefile.am
	fi
done

fi
done

IFS=$OLD_IFS
