
# Include dependencies:
find_package(GTK2 COMPONENTS gtk gtkmm REQUIRED)
#find_package(GtkMM REQUIRED)
find_package(SigC++ REQUIRED)
find_package(XML2 REQUIRED)
find_package(XSLT REQUIRED)
find_package(GSL REQUIRED)
find_package(ImageMagick++ REQUIRED)
find_package(Freetype2 REQUIRED)
find_package(GnomeVFS2)
find_package(Boost REQUIRED)
find_package(BoehmGC REQUIRED)
find_package(LibWPG)
find_package(PNG REQUIRED) 
find_package(Popt REQUIRED)
find_package(OpenSSL)
INCLUDE(IncludeJava)
# end Dependencies

#Linking 
LIST(APPEND INKSCAPE_LIBS 
${GTK2_LIBRARIES}
${SIGC++_LIBRARIES}
${GSL_LIBRARIES}
${XML2_LIBRARIES}
${XSLT_LIBRARIES}
${IMAGEMAGICK++_LIBRARIES}
${FREETYPE2_LIBRARIES}
${GNOMEVFS2_LIBRARIES}
${BOOST_LIBRARIES}
${BOEHMGC_LIBRARIES}
${PNG_LIBRARIES}
${POPT_LIBRARIES}
${OPENSSL_LIBRARIES}
)

#Includes 
SET(INK_INCLUDES
${CMAKE_BINARY_DIR}
${PROJECT_SOURCE_DIR}
${PROJECT_SOURCE_DIR}/src
${GTK2_INCLUDE_DIRS}
${SIGC++_INCLUDE_DIRS}
${GSL_INCLUDE_DIRS}
${XML2_INCLUDE_DIRS}
${XSLT_INCLUDE_DIRS}
${IMAGEMAGICK++_INCLUDE_DIRS}
${FREETYPE2_INCLUDE_DIRS}
${GNOMEVFS2_INCLUDE_DIRS}
${BOOST_INCLUDE_DIRS}
${BOEHMGC_INCLUDE_DIRS}
${PNG_INCLUDE_DIRS}
${POPT_INCLUDE_DIRS}
${OPENSSL_INCLUDE_DIRS}
)
#C/C++ Flags
INCLUDE_DIRECTORIES(${INK_INCLUDES})

#INCLUDE(ConfigCompileFlags)
INCLUDE(ConfigChecks)
