
# Include dependencies:
find_package(GTK2 REQUIRED)
find_package(GtkMM REQUIRED)
#find_package(SigC++ REQUIRED)
find_package(XML2 REQUIRED)
find_package(XSLT REQUIRED)
find_package(GSL REQUIRED)
find_package(ImageMagick++ REQUIRED)
find_package(Freetype2 REQUIRED)
find_package(GnomeVFS2)
find_package(Boost REQUIRED)
find_package(BoehmGC REQUIRED)
find_package(LibWPG)
find_package(PNG REQUIRED) 
find_package(Popt REQUIRED)
find_package(OpenSSL)
INCLUDE(IncludeJava)
# end Dependencies
Message(STATUS "${GTKMM_LIBRARIES}-----${GTKMM_INCLUDE_DIRS}")
#Linking 
SET(INKSCAPE_LIBS 
"${GTK2_LIBRARIES}"
"${GTKMM_LIBRARIES}"
#"${SIGC++_LIBRARIES}"
"${XML2_LIBRARIES}"
"${XSLT_LIBRARIES}"
"${IMAGEMAGICK++_LIBRARIES}"
"${FREETYPE2_LIBRARIES}"
"${GNOMEVFS2_LIBRARIES}"
"${BOOST_LIBRARIES}"
"${BOEHMGC_LIBRARIES}"
"${PNG_LIBRARIES}"
"${POPT_LIBRARIES}"
"${OPENSSL_LIBRARIES}"
)

#Includes 
INCLUDE_DIRECTORIES( 
${GTK2_INCLUDE_DIRS}
${GTKMM_INCLUDE_DIRS}
#${SIGC++_INCLUDE_DIRS}
${XML2_INCLUDE_DIRS}
${XSLT_INCLUDE_DIRS}
${IMAGEMAGICK++_INCLUDE_DIRS}
${FREETYPE2_INCLUDE_DIRS}
${GNOMEVFS2_INCLUDE_DIRS}
${BOOST_INCLUDE_DIRS}
${BOEHMGC_INCLUDE_DIRS}
${PNG_INCLUDE_DIRS}
${POPT_INCLUDE_DIRS}
${OPENSSL_INCLUDE_DIRS}
${CMAKE_BINARY_DIR}
${PROJECT_SOURCE_DIR}
${CMAKE_BINARY_DIR}/src
)
#C/C++ Flags
#SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -I${BOOST_INCLUDE_DIR} ")

#INCLUDE(ConfigCompileFlags)
INCLUDE(ConfigChecks)
