# figure out Python flags
FIND_PACKAGE(PythonInterp)
IF(PYTHONINTERP_FOUND)
  EXEC_PROGRAM(${PYTHON_EXECUTABLE}
               ARGS ${CMAKE_SOURCE_DIR}/makelib/python_config_var.py LIBS
               OUTPUT_VARIABLE PYTHON_LINK_LIBRARIES )
  EXEC_PROGRAM(${PYTHON_EXECUTABLE}
               ARGS ${CMAKE_SOURCE_DIR}/makelib/python_config_var.py LINKFORSTATIC
               OUTPUT_VARIABLE PYTHON_LINKFORSTATIC )
ELSE(PYTHONINTERP_FOUND)
  SET(PYTHON_LINK_LIBRARIES "")
  SET(PYTHON_LINKFORSTATIC "")               
ENDIF(PYTHONINTERP_FOUND)
