/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class placement_SolveVPSC */

#ifndef _Included_placement_SolveVPSC
#define _Included_placement_SolveVPSC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     placement_SolveVPSC
 * Method:    solve
 * Signature: ([Ljava/lang/String;[D[D[I[I[D[DI)D
 */
JNIEXPORT jdouble JNICALL Java_placement_SolveVPSC_solve
  (JNIEnv *, jobject, jobjectArray, jdoubleArray, jdoubleArray, jintArray, jintArray, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     placement_SolveVPSC
 * Method:    generateXConstraints
 * Signature: ([D[D[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_placement_SolveVPSC_generateXConstraints
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     placement_SolveVPSC
 * Method:    generateYConstraints
 * Signature: ([D[D[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_placement_SolveVPSC_generateYConstraints
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     placement_SolveVPSC
 * Method:    getConstraints
 * Signature: ([I[I[D)V
 */
JNIEXPORT void JNICALL Java_placement_SolveVPSC_getConstraints
  (JNIEnv *, jobject, jintArray, jintArray, jdoubleArray);

/*
 * Class:     placement_SolveVPSC
 * Method:    removeOverlaps
 * Signature: ([D[D[D[D)V
 */
JNIEXPORT void JNICALL Java_placement_SolveVPSC_removeOverlaps
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
