#!/bin/bash
#
# Author: Aaron Voisine <aaron@voisine.org>
# Inkscape Modifications: Michael Wybrow <mjwybrow@users.sourceforge.net>
# Inkscape Modifications: ~suv <suv-sf@users.sourceforge.net>

get_env_current ()
{
	env | awk -F= '/[a-zA-Z_][a-zA-Z_0-9]*=/ {if (!system("[ -n \"${" $1 "+y}\" ]")) print $1 }' | sort | uniq
}
[ -z "$_env_orig" ] && export _env_orig="$(get_env_current)"

CWD="$(cd "$(dirname "$0")" && pwd)"

source "${CWD}/xdg_setup.sh"

exec "$CWD/bin/inkscape" "$@"
