#!/bin/bash
#
# Author: Aaron Voisine <aaron@voisine.org>
# Inkscape Modifications: Michael Wybrow <mjwybrow@users.sourceforge.net>
# Inkscape Modifications: ~suv <suv-sf@users.sourceforge.net>

CWD="$(cd "$(dirname "$0")" && pwd)"

source "${CWD}/xdg_setup.sh"

exec "$CWD/bin/inkscape" "$@"
